server:
  port: 9527

spring:
  application:
    name: ruoyi-gateway

  devtools:
    restart:
      enabled: true   #开启热部署

  profiles:
    active: dev       #配置文件路径

  cloud:
    config:
      fail-fast: true #即在获取不到远程配置时，立即失败，但是用下边的配置进行重试
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: ruoyi-config
    gateway:
      discovery:
        locator:
          enabled: true
      routes:         #路由配置
        # 认证中心
        - id: ruoyi-auth          #自定义的路由ID,保持唯一
          uri: lb://ruoyi-auth    #目标服务地址
          predicates:             #路由条件
            - Path=/auth/**
          filters:                #过滤规则
            # 验证码处理
            - CacheRequest
            - ImgCodeFilter
            - StripPrefix=1
#        # 代码生成
#        - id: ruoyi-gen
#          uri: lb://ruoyi-gen
#          predicates:
#            - Path=/gen/**
#          filters:
#            - StripPrefix=1
#        # dfs  文件
#        - id: ruoyi-dfs
#          uri: lb://ruoyi-dfs
#          predicates:
#            - Path=/dfs/**
#          filters:
#            - StripPrefix=1
        #system 模块
        - id: ruoyi-system
          uri: lb://ruoyi-system
          predicates:
            - Path=/system/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'

eureka:
  client:
    service-url:                      # 客户端注册进eureka服务列表内
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms


