server:
  port: 8001

# 日志配置
logging:
  level:
    com.ityouzi: debug
    org.springframework: warn   # 服务器警告

spring:
  application:
    name: ruoyi-system
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: ruoyi-config
  profiles:
    active: dev
  devtools:           #热启动
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      max-request-size: 10MB  # 单位必须大写MB或不写(即为B)
      max-file-size: 5MB

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true     # 访问路径可以显示IP地址
    instance-id: ${spring.application.name}:${server.port}



# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# MyBatis
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.ityouzi
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml

mapper:
  not-empty: true
  identity: MYSQL

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql